### ISSUE TITLE
fix: selection is not possible in the page

### ISSUE THREAD

**Issue by ankitkushawaha1000** [deepak-gangwar/note-chrome-extension#64]

**Comment by ankitkushawaha1000** [comment]
this problem has arrived after using framer-motion I guess....

**Comment by ankitkushawaha1000** [comment]
closed by mistake

**Comment by deepak-gangwar** [comment]
I fixed the issue. It was an issue caused by the dragBoundary div we are using to create a boundary for the panel to be dragged over. It was coming over the text. Sent it to the back. Now everything is working
